force-app/main/default/objects/VRT_Vehicle__c/VRT_Vehicle__c.object-meta.xml
<CustomObject>
    <description>Medio de transporte a alquilar.</description>
    <label>Vehículo</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Vehículo Number.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Vehículos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/VRT_Vehicle__c/fields/VRT_FLG_NeedsInspection__c.field-meta.xml
<CustomField>
    <fullName>VRT_FLG_NeedsInspection__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Registra si un vehículo debe o no pasar la ITV.</description>
    <label>Necesita pasar inspección (ITV)</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/VRT_Vehicle__c/fields/VRT_SEL_VehicleType__c.field-meta.xml
<CustomField>
    <fullName>VRT_SEL_VehicleType__c</fullName>
    <description>Diferentes tipos de vehículos disponibles para alquiler.</description>
    <label>Tipo de vehículo</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Coche</fullName>
            </value>
            <value>
                <fullName>Moto</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/VRT_CLS_CheckVehicleRevision.cls
public class VRT_CLS_CheckVehicleRevision implements Database.Batchable<SObject> {
    public Database.QueryLocator start(Database.BatchableContext bc) {
        // Aquí va la QUERY
        Database.QueryLocator query = Database.getQueryLocator(
            'SELECT Id, VRT_DAT_ManufacturedYear__c, VRT_SEL_VehicleType__c, VRT_FLG_NeedsInspection__c FROM VRT_Vehicle__c WHERE VRT_FLG_NeedsInspection__c = false');

        return query;
    }

    public void execute(Database.BatchableContext bc, List<sObject> scope) {
        // Aquí va la lógica de Coche/Moto y el Update

        // Creamos una lista para los que realmente cambien
        List<VRT_Vehicle__c> vehiclesToUpdate = new List<VRT_Vehicle__c>();


        for (VRT_Vehicle__c vehicle : (List<VRT_Vehicle__c>)scope) {
            if (vehicle.VRT_DAT_ManufacturedYear__c != null) {
                Integer anioFabricacion = vehicle.VRT_DAT_ManufacturedYear__c.year();
                Integer anioActual = Date.today().year();

                if (vehicle.VRT_SEL_VehicleType__c == 'Coche' &&
                    (anioActual - anioFabricacion >= 4) ||
                    vehicle.VRT_SEL_VehicleType__c == 'Moto' &&
                    (anioActual - anioFabricacion >= 3)) {
                        vehicle.VRT_FLG_NeedsInspection__c = true;
                        vehiclesToUpdate.add(vehicle);
                }
            }
        }

        if (!vehiclesToUpdate.isEmpty()) {
            update vehiclesToUpdate;
        }
    }

    public void finish(Database.BatchableContext bc) {
        // Tareas finales (o vacío si no necesitas nada)
    }
}