force-app/main/default/objects/VRT_Vehicle__c/VRT_Vehicle__c.object-meta.xml
<CustomObject>
    <description>Medio de transporte a alquilar.</description>
    <label>Vehículo</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Vehículo Number.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Vehículos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/VRT_Vehicle__c/fields/VRT_SEL_Status__c.field-meta.xml
<CustomField>
    <fullName>VRT_SEL_Status__c</fullName>
    <description>Indica si el vehículo está listo para el alquiler o requiere mantenimiento.</description>
    <label>Estado</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Listo</fullName>
            </value>
            <value>
                <fullName>En mantenimiento</fullName>
            </value>
            <value>
                <fullName>Fuera de servicio</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/VRT_Vehicle__c/fields/VRT_SEL_VehicleType__c.field-meta.xml
<CustomField>
    <fullName>VRT_SEL_VehicleType__c</fullName>
    <description>Diferentes tipos de vehículos disponibles para alquiler.</description>
    <label>Tipo de vehículo</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Coche</fullName>
            </value>
            <value>
                <fullName>Moto</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/VRT_LWC_FleetSearchController.cls
public with sharing class VRT_LWC_FleetSearchController {

    /**
     * 1. Recuperar la flota de vehículos con todos los campos necesarios utilizando el texto recibido
     * Se usa @AuraEnabled(cacheable=true) porque es una lectura que se conectará con @wire en LWC.
     */
    @AuraEnabled(cacheable=true)
    public static List<VRT_Vehicle__c> getFleetSearched(String searchTerm) {
        if (searchTerm == null || searchTerm.trim() == '' || searchTerm.length() < 2) {
            return new List<VRT_Vehicle__c>();
        }

        String searchPattern = '%' + searchTerm + '%';

        return [
            SELECT Id, Name, VRT_SEL_VehicleType__c, VRT_TXT_Brand__c, VRT_TXT_Model__c, VRT_TXT_LicensePlate__c, VRT_SEL_Status__c
            FROM VRT_Vehicle__c
            WHERE (
                VRT_TXT_Brand__c LIKE :searchPattern
                OR VRT_TXT_Model__c LIKE :searchPattern
                OR VRT_TXT_LicensePlate__c LIKE :searchPattern
            )
            ORDER BY Name ASC
            LIMIT 50
        ];
    }
}