force-app/main/default/objects/VRT_Vehicle__c/VRT_Vehicle__c.object-meta.xml
<CustomObject>
    <description>Medio de transporte a alquilar.</description>
    <label>Vehículo</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Vehículo Number.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Vehículos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/VRT_Vehicle__c/fields/VRT_FLG_NeedsInspection__c.field-meta.xml
<CustomField>
    <fullName>VRT_FLG_NeedsInspection__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Registra si un vehículo debe o no pasar la ITV.</description>
    <label>Necesita pasar inspección (ITV)</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/VRT_Vehicle__c/fields/VRT_NUM_Passengers__c.field-meta.xml
<CustomField>
    <fullName>VRT_NUM_Passengers__c</fullName>
    <description>Campo numérico para especificar el número de pasajeros permitidos.</description>
    <label>Pasajeros</label>
    <precision>2</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/VRT_Vehicle__c/fields/VRT_SEL_EnergyType__c.field-meta.xml
<CustomField>
    <fullName>VRT_SEL_EnergyType__c</fullName>
    <description>Campo picklist para especificar el tipo de combustible o energía del vehículo.</description>
    <label>Combustible</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Eléctrico</fullName>
            </value>
            <value>
                <fullName>Híbrido</fullName>
            </value>
            <value>
                <fullName>Gasolina</fullName>
            </value>
            <value>
                <fullName>Diesel</fullName>
            </value>
            <value>
                <fullName>Otro</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/VRT_Vehicle__c/fields/VRT_SEL_Status__c.field-meta.xml
<CustomField>
    <fullName>VRT_SEL_Status__c</fullName>
    <description>Indica si el vehículo está listo para el alquiler o requiere mantenimiento.</description>
    <label>Estado</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Listo</fullName>
            </value>
            <value>
                <fullName>En mantenimiento</fullName>
            </value>
            <value>
                <fullName>Fuera de servicio</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/VRT_Vehicle__c/fields/VRT_SEL_VehicleType__c.field-meta.xml
<CustomField>
    <fullName>VRT_SEL_VehicleType__c</fullName>
    <description>Diferentes tipos de vehículos disponibles para alquiler.</description>
    <label>Tipo de vehículo</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Coche</fullName>
            </value>
            <value>
                <fullName>Moto</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/VRT_CLS_CheckVehicleRevision_Test.cls
@isTest
public class VRT_CLS_CheckVehicleRevision_Test {

    @isTest
    static void testBatchRevision() {
        // 1. Preparación de datos (Data Setup)
        List<VRT_Vehicle__c> vehicles = new List<VRT_Vehicle__c>();

        VRT_Vehicle__c inspectionCar = new VRT_Vehicle__c(
            VRT_SEL_VehicleType__c = 'Coche',
            VRT_TXT_LicensePlate__c = 'inspect',
            VRT_DAT_ManufacturedYear__c = Date.today().addYears(-5),
            VRT_FLG_NeedsInspection__c = false,
            VRT_NUM_Passengers__c = 4,
            VRT_SEL_EnergyType__c = 'Gasolina',
            VRT_SEL_Status__c = 'Listo',
            VRT_TXT_Brand__c = 'Dacia',
            VRT_TXT_Model__c = 'Sandero'
        );
        vehicles.add(inspectionCar);

        VRT_Vehicle__c newCar = new VRT_Vehicle__c(
            VRT_SEL_VehicleType__c = 'Coche',
            VRT_TXT_LicensePlate__c = 'noInspe',
            VRT_DAT_ManufacturedYear__c = Date.today().addYears(-2),
            VRT_FLG_NeedsInspection__c = false,
            VRT_NUM_Passengers__c = 4,
            VRT_SEL_EnergyType__c = 'Eléctrico',
            VRT_SEL_Status__c = 'Listo',
            VRT_TXT_Brand__c = 'Peugeot',
            VRT_TXT_Model__c = 'e-208'
        );
        vehicles.add(newCar);

        VRT_Vehicle__c inspectionBike = new VRT_Vehicle__c(
            VRT_SEL_VehicleType__c = 'Moto',
            VRT_TXT_LicensePlate__c = 'inspect',
            VRT_DAT_ManufacturedYear__c = Date.today().addYears(-4),
            VRT_FLG_NeedsInspection__c = false,
            VRT_NUM_Passengers__c = 2,
            VRT_SEL_EnergyType__c = 'Diesel',
            VRT_SEL_Status__c = 'Listo',
            VRT_TXT_Brand__c = 'Kawasaki',
            VRT_TXT_Model__c = 'Ninja'
        );
        vehicles.add(inspectionBike);

        VRT_Vehicle__c newBike = new VRT_Vehicle__c(
            VRT_SEL_VehicleType__c = 'Moto',
            VRT_TXT_LicensePlate__c = 'noInspe',
            VRT_DAT_ManufacturedYear__c = Date.today().addYears(-2),
            VRT_FLG_NeedsInspection__c = false,
            VRT_NUM_Passengers__c = 2,
            VRT_SEL_EnergyType__c = 'Híbrido',
            VRT_SEL_Status__c = 'Listo',
            VRT_TXT_Brand__c = 'BMW',
            VRT_TXT_Model__c = 'CE 02'
        );
        vehicles.add(newBike);

        insert vehicles;

        // 2. Ejecución
        // Todo proceso asíncrono debe ir entre startTest y stopTest
        Test.startTest();
        VRT_CLS_CheckVehicleRevision batch = new VRT_CLS_CheckVehicleRevision();
        Database.executeBatch(batch);
        Test.stopTest(); // Aquí es donde Salesforce fuerza la ejecución del Batch

        // 3. Verificación (Asserts)
        // Volvemos a consultar el registro para ver si el Batch lo cambió
        VRT_Vehicle__c[] UpdatedOldVehicles = [
            SELECT VRT_FLG_NeedsInspection__c, VRT_TXT_Brand__c, VRT_TXT_Model__c
            FROM VRT_Vehicle__c
            WHERE VRT_TXT_LicensePlate__c = 'inspect'];

        VRT_Vehicle__c[] UpdatedNewVehicles = [
            SELECT VRT_FLG_NeedsInspection__c, VRT_TXT_Brand__c, VRT_TXT_Model__c
            FROM VRT_Vehicle__c
            WHERE VRT_TXT_LicensePlate__c = 'noInspe'];

        // Comprobamos que el booleano ahora es true
       for (VRT_Vehicle__c vehicle : UpdatedOldVehicles) {
        Assert.areEqual(true, vehicle.VRT_FLG_NeedsInspection__c, vehicle.VRT_TXT_Brand__c + ' ' + vehicle.VRT_TXT_Model__c + ' DEBERÍA necesitar inspección');
       }

        // Comprobamos que el booleano sigue siendo false
       for (VRT_Vehicle__c vehicle : UpdatedNewVehicles) {
        Assert.areEqual(false, vehicle.VRT_FLG_NeedsInspection__c, vehicle.VRT_TXT_Brand__c + ' ' + vehicle.VRT_TXT_Model__c + ' NO debería necesitar inspección');
       }
    }
}